<?
$array_title = array (
		"ADir",
		"AO.Prof.",
		"Arch.",
		"Arch.Ing.",
		"Arch.Prof.",
		"Ass.",
		"Ass.Prof.",
		"B.A.",
		"B.Ac.",
		"B.B.A.",
		"B.chin.Pharm.",
		"B.Eng.",
		"B.phil.",
		"B.rer.nat.",
		"B.S.",
		"B.Sc.",
		"B.Tui.",
		"BA",
		"BA pth",
		"Bacc.theol.",
		"Bakk.",
		"Bakk. Pfl.",
		"Bakk.(FH)",
		"Bakk.art.",
		"Bakk.Betr.W.Ges.",
		"Bakk.Biomed.Inf.",
		"Bakk.iur.",
		"Bakk.phil.",
		"Bakk.Psych.",
		"Bakk.rer.nat.",
		"Bakk.rer.soc.oec.",
		"Bakk.techn.",
		"BBA",
		"BEd.",
		"BLit.",
		"BM.",
		"BR.",
		"BR.hc.",
		"BR.hc.Prof.",
		"BSc",
		"C.Eng.",
		"ChB.",
		"DDDr.",
		"DDI",
		"DDI.Dolm.",
		"DDI.Dr.",
		"DDI.Mag.Dr.",
		"DDr.",
		"DDr.Mag.",
		"DI",
		"DI Arch.",
		"DI DDr.",
		"DI Dkfm.",
		"DI Dr.",
		"DI Dr.Mag.",
		"DI Dr.Prof.",
		"DI HTL",
		"DI Kom Rat",
		"DI Mag (FH)",
		"DI Mag.",
		"Di Msc.",
		"DI Prof.",
		"DI-(FH)",
		"DI.Dkfm.Dr.",
		"DI.Dr.hc",
		"DI.Dr.techn.",
		"DI(FH)",
		"Dipl-Tierarzt",
		"Dipl.-Ing.",
		"Dipl.-Ing.(FH)",
		"Dipl.-Ing.Biomed.Inf.",
		"Dipl.Ass.",
		"Dipl.BW",
		"Dipl.BW Dr.",
		"Dipl.BW Mag.",
		"Dipl.Dolm.",
		"Dipl.Dolm.Dr.",
		"Dipl.Dolm.Mag",
		"Dipl.Erg.",
		"Dipl.Graph.",
		"Dipl.Graph.Ma",
		"Dipl.Innenarc",
		"Dipl.Kosm.",
		"Dipl.Kosm.Mag",
		"Dipl.Log.",
		"Dipl.Log.Mag.",
		"Dipl.Ök",
		"Dipl.Ök Dr.",
		"Dipl.Ök Mag.",
		"Dipl.Opt.",
		"Dipl.Päd.",
		"Dipl.Pharm.",
		"Dipl.Phil.",
		"Dipl.Phys.",
		"Dipl.Psych.",
		"Dipl.PT.",
		"Dipl.Rest.",
		"Dipl.SA.",
		"Dipl.Soz.Theo",
		"Dipl.TA.DDr.",
		"Dipl.TA.Dr.",
		"Dipl.TA.Ing.",
		"Dipl.TA.Ing.D",
		"Dipl.TA.Mag.",
		"Dipl.TA.Mag.D",
		"Dipl.Theol.",
		"Dipl.Übers.",
		"Dipl.Vw.",
		"Dipl.Vw.Dr.",
		"Dipl.Vw.Dr.",
		"Dipl.Vw.Mag.",
		"Dipl.Vw.Mag.D",
		"Dir",
		"Dir.OA.",
		"Dir.Prim.",
		"Dkffr.",
		"Dkfm.",
		"Dkfm.DDr.",
		"Dkfm.DI.",
		"Dkfm.Dr.",
		"Dkfm.Ing.",
		"Dkfm.Mag.",
		"Dkfm.Mag.DDr.",
		"Dkfm.Mag.Dr.",
		"Dkfm.MMag.",
		"Dkfm.MMag.DDr",
		"Dkfm.Prof.",
		"Doc.",
		"Dott.",
		"Doz.",
		"Doz.DDr.",
		"Doz.DI Dr.",
		"Doz.Dr.",
		"Doz.Dr.Mag.",
		"Doz.Mag.",
		"Doz.Prim.",
		"Doz.Prof.",
		"Dr.",
		"Dr.Dipl.Vw.",
		"Dr.Dkfm.",
		"Dr.Dr.med.",
		"Dr.hc.",
		"Dr.Ing.",
		"Dr.iur.",
		"Dr.LL.M.RA",
		"Dr.Mag.",
		"Dr.Mag.Ing.",
		"Dr.med.",
		"Dr.Med.-Inf.",
		"Dr.med.dent.",
		"Dr.med.dent.et scient.med.",
		"Dr.med.univ.",
		"Dr.med.univ.et med.dent.",
		"Dr.med.univ.et scient.med.",
		"Dr.med.vet.",
		"Dr.MMag.",
		"Dr.mont.",
		"Dr.nat.techn.",
		"Dr.Pfl.",
		"Dr.phil.",
		"Dr.phil.Dr.ju",
		"Dr.phil.fac.theol.",
		"Dr.RA",
		"Dr.rer.nat.",
		"Dr.rer.pol.",
		"Dr.rer.soc.oec.",
		"Dr.scient.med.",
		"Dr.techn.",
		"Dr.theol.",
		"Dr.Univ.",
		"EMHRD",
		"EMLE",
		"EMPH",
		"Eng.",
		"Exec.MBA",
		"HR",
		"HR DI",
		"HR Dr.",
		"HR Ing.",
		"HR Mag.",
		"HR.Prof.",
		"Ing.",
		"Ing.Arch.",
		"Ing.DDr.",
		"Ing.DI",
		"Ing.DI.Dr.",
		"Ing.Dkfm.",
		"Ing.Dkfm.Dr.",
		"Ing.Dkfm.Mag.",
		"Ing.Dr.",
		"Ing.Dr.Mag.",
		"Ing.Ing.",
		"Ing.Kom Rat",
		"Ing.Mag.",
		"Ing.Mag.(FH)",
		"Ing.Mag.arch.",
		"Ing.MMag.",
		"Ing.MMag.arch",
		"Ing.Prof.",
		"Ing.Prof.Dr.",
		"Ing.RegR",
		"Int.MLA",
		"KmzlR.Prof.",
		"Kom Rat",
		"Kom Rat Dr.",
		"KR",
		"KR Dr.",
		"KR Ing.",
		"KR Mag.",
		"KR MMag.",
		"Lic.theol.",
		"LL.B.",
		"LL.M.",
		"LLB",
		"LLM",
		"LOSanR.",
		"LOSanR.MR.",
		"LOVetR.",
		"LSanR.",
		"LVetR.",
		"LVetR.HR.",
		"M.A.",
		"M.A.I.S.",
		"M.Ac.",
		"M.B.L.",
		"M.chin.Pharm.",
		"M.E.S.",
		"M.Ed.",
		"M.rer.nat.",
		"M.Sc.",
		"M.TCM.",
		"M.Tui.",
		"MA",
		"Mag.",
		"Mag.(FH)",
		"Mag.arch.",
		"Mag.art.",
		"Mag.DDr.",
		"Mag.des.ind.",
		"Mag.Dr.",
		"Mag.Dr.med.",
		"Mag.Dr.med.ve",
		"Mag.Dr.Prof.",
		"Mag.Dr.rer.na",
		"Mag.Inf.Med.",
		"Mag.Ing.",
		"Mag.iur.",
		"Mag.iur.rer.oec.",
		"Mag.jur.Dr.",
		"Mag.Komm.",
		"Mag.LL.M.",
		"Mag.Mba Msc",
		"Mag.med.",
		"Mag.med.vet.",
		"Mag.med.vet.",
		"Mag.Pfl.",
		"Mag.pharm.",
		"Mag.phil.",
		"Mag.phil.Dr.",
		"Mag.phil.Dr.m",
		"Mag.phil.fac.theol.",
		"Mag.pth",
		"Mag.rer.nat.",
		"Mag.rer.soc.oec",
		"Mag.theol.",
		"MAS",
		"Mastère",
		"MBA",
		"MCoach",
		"MD",
		"MDes",
		"MDSc",
		"Mech.Eng.",
		"MedR DDr.",
		"MedR Dr.",
		"MedR.",
		"MedR.HR.",
		"MedR.OA.",
		"MedR.OSanR.",
		"MedR.Prim.",
		"MedR.Prof.",
		"MedR.wHR.",
		"MEM",
		"MEng",
		"MFA",
		"MFP",
		"MIB",
		"MIBI",
		"MIM",
		"MinR",
		"MinR Dr.",
		"MinR Mag.",
		"MinR.",
		"MinR.MedR.",
		"MLit.",
		"MLL",
		"MLS",
		"MM.",
		"MMag.",
		"MMag.DDr.",
		"MMag.Dr.",
		"MMedScAA",
		"MPA",
		"MPC",
		"MPH",
		"MPhil",
		"MPM",
		"MPOS",
		"MR.Prim.HR.",
		"MSc",
		"Msc.",
		"MScMF",
		"MSd",
		"MSPT",
		"MTD",
		"MTox",
		"O.Prof.",
		"O.Univ.Prof.",
		"OA.",
		"OA.Doz.",
		"OA.HR.",
		"OA.Prof.",
		"OkR.",
		"OMedR Dr.",
		"OMedR.",
		"OMedR.Doz.",
		"OMedR.HR.",
		"OMedR.OA.",
		"OMedR.Prim.",
		"OMedR.Prof.",
		"OR.",
		"OR.MR.Prim.",
		
		"ORegR." 
);