ALTER TABLE orders 
ADD COLUMN closed_at DATETIME NULL,
ADD COLUMN closing_price DECIMAL(10,2) NULL,
ADD COLUMN pnl DECIMAL(10,2) NULL,
ADD COLUMN tp_order_id VARCHAR(50) NULL,
ADD COLUMN sl_order_id VARCHAR(50) NULL;
