<?php

$rahmenfarbe  = array(0,0,0);
/*****************************************************
TABLE DEFAULT DEFINES
*****************************************************/
	$table_default_header_type = array(
					/*'WIDTH' => 6,
					//'T_COLOR' => array(40,40,40),
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 8,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BRD_COLOR' => array(100,100,100),
					'BRD_SIZE' => 0.1,
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);*/
					
					//'WIDTH' => 6,
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 8,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					);
	//Kopfzeile Falk				
	$table_default_header_type1 = array(
					'WIDTH' => 6,
					//'T_COLOR' => array(40,40,40),
					'T_SIZE' => 9,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => array(230,230,230),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => '',
					'TEXT' => '',
					);				
	$table_default_data_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 8,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'N',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					);
	//Vorlage FALK				
	$table_default_data_type1 = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 9,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'N',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 5,   //Abstaende im Textfeld
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					);
	$table_default_table_type = array(
					'TB_ALIGN' => 'L',
					'L_MARGIN' => 1.5,
					//'BRD_COLOR' => array(100,100,100),
					//'BRD_COLOR' => array(180,180,180),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,
					'LN_SIZE' => 4, 
					);
	//Auflistung der Artikel&uuml;bersicht
	$table_head_liste_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 7,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 5,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					);				
									
	
	
	$table_liste_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 7,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'N',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 4,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					);				
					
	$table_default_foot_type = array(
					'T_COLOR' => array(0,0,0),
					'T_SIZE' => 8,
					'T_FONT' => 'Arial',
					'T_ALIGN' => 'C',
					'V_ALIGN' => 'T',
					'T_TYPE' => '',
					'LN_SIZE' => 6,
					'BG_COLOR' => array(255,255,255),
					'BRD_COLOR' => $rahmenfarbe,
					'BRD_SIZE' => 0.1,	
					'BRD_TYPE' => '1',
					'BRD_TYPE_NEW_PAGE' => ''
					
					);
/*****************************************************
TABLE DEFAULT DEFINES --- END
*****************************************************/
?>