<?php
// Setzt Table auf UTF 8
function fix_utf8_table($fix_table) {
	//$GLOBALS['mysqli']->query ( "ALTER TABLE $fix_table CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci" ) or die ( mysqli_error ($GLOBALS['mysqli']) );
}

// Wandelt Sonderzeichen id Column richtig um
function fix_utf8_column($fix_table,$fix_column) {
	//$GLOBALS['mysqli']->query ( "DELIMITER $$ CREATE FUNCTION maybe_utf8_decode(str text charset utf8) RETURNS text CHARSET utf8 DETERMINISTIC BEGIN declare str_converted text charset utf8; declare max_error_count int default @@max_error_count; set @@max_error_count = 0; set str_converted = convert(binary convert(str using latin1) using utf8), set @@max_error_count = max_error_count; if @@warning_count > 0 then return str; else return str_converted; end if; END$$ DELIMITER ; update $fix_table set $fix_column = maybe_utf8_decode(internet_title)," ) or die ( mysqli_error ($GLOBALS['mysqli']) );
	
	return "UPDATE `$fix_table` set
	`$fix_column`= REPLACE(`$fix_column`,'ÃŸ', 'ß'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ã¤', 'ä'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ã¼', 'ü'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ã¶', 'ö'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ã„', 'Ä'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ãœ', 'Ü'),
	`$fix_column`= REPLACE(`$fix_column`, 'Ã–', 'Ö'),
	`$fix_column`= REPLACE(`$fix_column`, 'â‚¬', '€'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã‰','É'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã‡','Ç'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ãƒ','Ã'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã ','À'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ãº','ú'),
	`$fix_column`= REPLACE(`$fix_column` ,'â€¢','-'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã˜','Ø'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ãµ','õ'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã­','í'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã¢','â'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã£','ã'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ãª','ê'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã¡','á'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã©','é'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã³','ó'),
	`$fix_column`= REPLACE(`$fix_column` ,'â€“','–'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã§','ç'),
	`$fix_column`= REPLACE(`$fix_column` ,'Âª','ª'),
	`$fix_column`= REPLACE(`$fix_column` ,'Âº','º'),
	`$fix_column`= REPLACE(`$fix_column` ,'Ã ','à')
	";
}	


function fix_utf8_entities_column($fix_table,$fix_column) {
	return "UPDATE `$fix_table` set
	`$fix_column`= REPLACE(`$fix_column` ,'&ccedil;','ç'),
	`$fix_column`= REPLACE(`$fix_column` ,'&atilde;','ã'),
	`$fix_column`= REPLACE(`$fix_column` ,'&aacute;','á'),
	`$fix_column`= REPLACE(`$fix_column` ,'&acirc;','â'),
	`$fix_column`= REPLACE(`$fix_column` ,'&eacute;','é'),
	`$fix_column`= REPLACE(`$fix_column` ,'&iacute;','í'),
	`$fix_column`= REPLACE(`$fix_column` ,'&otilde;','õ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&uacute;','ú'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ccedil;','ç'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Aacute;','Á'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Acirc;','Â'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Eacute;','É'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Iacute;','Í'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Otilde;','Õ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Uacute;','Ú'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Ccedil;','Ç'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Atilde;','Ã'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Agrave;','À'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Ecirc;','Ê'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Oacute;','Ó'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Ocirc;','Ô'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Uuml;','Ü'),
	`$fix_column`= REPLACE(`$fix_column` ,'&atilde;','ã'),
	`$fix_column`= REPLACE(`$fix_column` ,'&agrave;','à'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ecirc;','ê'),
	`$fix_column`= REPLACE(`$fix_column` ,'&oacute;','ó'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ocirc;','ô'),
	`$fix_column`= REPLACE(`$fix_column` ,'&uuml;','ü'),
	`$fix_column`= REPLACE(`$fix_column` ,'&amp;','&'),
	`$fix_column`= REPLACE(`$fix_column` ,'&gt;','>'),
	`$fix_column`= REPLACE(`$fix_column` ,'&lt;','<'),
	`$fix_column`= REPLACE(`$fix_column` ,'&circ;','ˆ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&tilde;','˜'),
	`$fix_column`= REPLACE(`$fix_column` ,'&uml;','¨'),
	`$fix_column`= REPLACE(`$fix_column` ,'&cute;','´'),
	`$fix_column`= REPLACE(`$fix_column` ,'&cedil;','¸'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ldquo;','“'),
	`$fix_column`= REPLACE(`$fix_column` ,'&rdquo;','”'),
	`$fix_column`= REPLACE(`$fix_column` ,'&lsquo;','‘'),
	`$fix_column`= REPLACE(`$fix_column` ,'&rsquo;','’'),
	`$fix_column`= REPLACE(`$fix_column` ,'&lsaquo;','‹'),
	`$fix_column`= REPLACE(`$fix_column` ,'&rsaquo;','›'),
	`$fix_column`= REPLACE(`$fix_column` ,'&laquo;','«'),
	`$fix_column`= REPLACE(`$fix_column` ,'&raquo;','»'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ordm;','º'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ordf;','ª'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ndash;','–'),
	`$fix_column`= REPLACE(`$fix_column` ,'&mdash;','—'),
	`$fix_column`= REPLACE(`$fix_column` ,'&macr;','¯'),
	`$fix_column`= REPLACE(`$fix_column` ,'&hellip;','…'),
	`$fix_column`= REPLACE(`$fix_column` ,'&brvbar;','¦'),
	`$fix_column`= REPLACE(`$fix_column` ,'&bull;','•'),
	`$fix_column`= REPLACE(`$fix_column` ,'&para;','¶'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sect;','§'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sup1;','¹'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sup2;','²'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sup3;','³'),
	`$fix_column`= REPLACE(`$fix_column` ,'&frac12;','½'),
	`$fix_column`= REPLACE(`$fix_column` ,'&frac14;','¼'),
	`$fix_column`= REPLACE(`$fix_column` ,'&frac34;','¾'),
	`$fix_column`= REPLACE(`$fix_column` ,'&#8539;','⅛'),
	`$fix_column`= REPLACE(`$fix_column` ,'&#8540;','⅜'),
	`$fix_column`= REPLACE(`$fix_column` ,'&#8541;','⅝'),
	`$fix_column`= REPLACE(`$fix_column` ,'&#8542;','⅞'),
	`$fix_column`= REPLACE(`$fix_column` ,'&gt;','>'),
	`$fix_column`= REPLACE(`$fix_column` ,'&lt;','<'),
	`$fix_column`= REPLACE(`$fix_column` ,'&plusmn;','±'),
	`$fix_column`= REPLACE(`$fix_column` ,'&minus;','−'),
	`$fix_column`= REPLACE(`$fix_column` ,'&times;','×'),
	`$fix_column`= REPLACE(`$fix_column` ,'&divide;','÷'),
	`$fix_column`= REPLACE(`$fix_column` ,'&lowast;','∗'),
	`$fix_column`= REPLACE(`$fix_column` ,'&frasl;','⁄'),
	`$fix_column`= REPLACE(`$fix_column` ,'&permil;','‰'),
	`$fix_column`= REPLACE(`$fix_column` ,'&int;','∫'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sum;','∑'),
	`$fix_column`= REPLACE(`$fix_column` ,'&prod;','∏'),
	`$fix_column`= REPLACE(`$fix_column` ,'&radic;','√'),
	`$fix_column`= REPLACE(`$fix_column` ,'&infin;','∞'),
	`$fix_column`= REPLACE(`$fix_column` ,'&asymp;','≈'),
	`$fix_column`= REPLACE(`$fix_column` ,'&cong;','≅'),
	`$fix_column`= REPLACE(`$fix_column` ,'&prop;','∝'),
	`$fix_column`= REPLACE(`$fix_column` ,'&equiv;','≡'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ne;','≠'),
	`$fix_column`= REPLACE(`$fix_column` ,'&le;','≤'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ge;','≥'),
	`$fix_column`= REPLACE(`$fix_column` ,'&there4;','∴'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sdot;','⋅'),
	`$fix_column`= REPLACE(`$fix_column` ,'&middot;','·'),
	`$fix_column`= REPLACE(`$fix_column` ,'&part;','∂'),
	`$fix_column`= REPLACE(`$fix_column` ,'&image;','ℑ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&real;','ℜ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&prime;','′'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Prime;','″'),
	`$fix_column`= REPLACE(`$fix_column` ,'&deg;','°'),
	`$fix_column`= REPLACE(`$fix_column` ,'&ang;','∠'),
	`$fix_column`= REPLACE(`$fix_column` ,'&perp;','⊥'),
	`$fix_column`= REPLACE(`$fix_column` ,'&nabla;','∇'),
	`$fix_column`= REPLACE(`$fix_column` ,'&oplus;','⊕'),
	`$fix_column`= REPLACE(`$fix_column` ,'&otimes;','⊗'),
	`$fix_column`= REPLACE(`$fix_column` ,'&alefsym;','ℵ'),
	`$fix_column`= REPLACE(`$fix_column` ,'&oslash;','ø'),
	`$fix_column`= REPLACE(`$fix_column` ,'&Oslash;','Ø'),
	`$fix_column`= REPLACE(`$fix_column` ,'&isin;','∈'),
	`$fix_column`= REPLACE(`$fix_column` ,'&notin;','∉'),
	`$fix_column`= REPLACE(`$fix_column` ,'&cap;','∩'),
	`$fix_column`= REPLACE(`$fix_column` ,'&cup;','∪'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sub;','⊂'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sup;','⊃'),
	`$fix_column`= REPLACE(`$fix_column` ,'&sube;','⊆'),
	`$fix_column`= REPLACE(`$fix_column` ,'&supe;','⊇'),
	`$fix_column`= REPLACE(`$fix_column` ,'&exist;','∃'),
	`$fix_column`= REPLACE(`$fix_column` ,'&forall;','∀'),
	`$fix_column`= REPLACE(`$fix_column` ,'&empty;','∅'),
	`$fix_column`= REPLACE(`$fix_column` ,'&not;','¬'),
	`$fix_column`= REPLACE(`$fix_column` ,'&and;','∧'),
	`$fix_column`= REPLACE(`$fix_column` ,'&or;','∨'),
	`$fix_column`= REPLACE(`$fix_column` ,'&crarr;','↵')
	";
}